// <auto-generated />
namespace CMS_Project.Migrations
{
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    public sealed partial class enas : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(enas));
        
        string IMigrationMetadata.Id
        {
            get { return "201711111442375_enas"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
