// <auto-generated />
namespace CMS_Project.Migrations
{
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    public sealed partial class qq : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(qq));
        
        string IMigrationMetadata.Id
        {
            get { return "201712061146433_qq"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return Resources.GetString("Source"); }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
