// <auto-generated />
namespace CMS_Project.Migrations
{
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    public sealed partial class test1 : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(test1));
        
        string IMigrationMetadata.Id
        {
            get { return "201711140059578_test1"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return Resources.GetString("Source"); }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
