// <auto-generated />
namespace CMS_Project.Migrations
{
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    public sealed partial class r3 : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(r3));
        
        string IMigrationMetadata.Id
        {
            get { return "201711121124076_r3"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
