// <auto-generated />
namespace CMS_Project.Migrations
{
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    public sealed partial class xx : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(xx));
        
        string IMigrationMetadata.Id
        {
            get { return "201711202227025_xx"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
